#!/bin/bash

if [[ -z "$1" ]]; then echo "Usage: $0 [jumphost]"; exit 1; fi

jumphost=$1
duo_version="1.9.11-1"
basedir=$(dirname $0)

function download_and_install {
    if [[ -z "$1" ]]; then echo "Usage: ${FUNCNAME} [jumphost hostname]"; return 1; fi

    local jumphost=$1

    ssh -t ec2-user@${jumphost} "sudo wget -P /usr/local/src https://s3-us-west-2.amazonaws.com/nubis-stacks/packages/rpm/duo_unix-${duo_version}.x86_64.rpm" > /dev/null 2>&1
    ssh -t ec2-user@${jumphost} "sudo rpm --import https://www.duosecurity.com/RPM-GPG-KEY-DUO" > /dev/null 2>&1
    ssh -t ec2-user@${jumphost} "sudo rpm -i /usr/local/src/duo_unix-${duo_version}.x86_64.rpm" > /dev/null 2>&1
    ssh -t ec2-user@${jumphost} "sudo chmod 0600 /etc/duo/*.conf" > /dev/null 2>&1
}

function copy_duo_puppet_module {
    if [[ -z "$1" ]]; then echo "Usage: ${FUNCNAME} [jumphost hostname]"; return 1; fi

    local jumphost=$1
    echo "Copying duo folder to ${jumphost} /tmp"
    scp -q -pr ${basedir}/duo ec2-user@${jumphost}:/tmp
    local RV=$?

    return ${RV}
}

download_and_install "${jumphost}"
