#!/bin/bash

. lib.sh || exit 1
set -u

read -p "What is the Account name : " account_name;
read -p "What is the AWS access key : " access_key;
read -p "What is the AWS secret key : " secret_key;

cat <<EOF > "${account_name}-nubis-bootstrap"
[${account_name}]
aws_access_key_id = ${access_key}
aws_secret_access_id = ${secret_key}
EOF

encrypt "${account_name}-nubis-bootstrap"
safedelete "${account_name}-nubis-bootstrap"
