#!/bin/bash
# Creates inline password policy for nubis-bootrap user

bootstrap_user="nubis-bootstrap"
admin_policy_doc="{\"Version\":\"2012-10-17\",\"Statement\":[{\"Action\":\"*\",\"Resource\":\"*\",\"Effect\":\"Allow\"}]}"

out=$(aws iam list-user-policies --user-name ${bootstrap_user} --query PolicyNames --output text | grep "admin")

if [ -z "${out}" ]; then
    echo "Creating inline policy for user: ${bootstrap_user}"
    aws iam put-user-policy --user-name "${bootstrap_user}" --policy-document "${admin_policy_doc}" --policy-name admin
fi
