#!/bin/bash

. lib.sh || exit 1
set -u

read -e -p "What is the Account name : " account_name;
read -e -p "What is the AWS access key : " access_key;
read -e -p "What is the AWS secret key : " secret_key;

cat <<EOF >  "${account_name}-nubis-bootstrap.json"
[
  {
    "account_id": "${account_name}",
    "aws_access_key_id": "${access_key}",
    "aws_secret_access_id": "${secret_key}"
  }
]
EOF

encrypt "${account_name}-nubis-bootstrap.json"
safedelete "${account_name}-nubis-bootstrap.json"
