#!/bin/bash
echo "Enforcing password policy"
aws iam update-account-password-policy\
    --allow-users-to-change-password\
    --max-password-age 90\
    --minimum-password-length 16\
    --password-reuse-prevention 24
